### ISSUE TITLE
Categories are hardcoded and limited

### ISSUE THREAD

**Issue by deepu-tp** [prdpx7/Pickup-line#1]
Pickuplinesgalore has many categories.
Would be nice to search for categories and configure pickup-line with categories of the user's choice.

**Comment by prdpx7** [comment]
yeah, I think we can do something like ```pickupline --keyword trump``` and then we soup all those categories on [pickuplinesgalore](https://www.pickuplinesgalore.com/) & do some regex match with keyword argument, and extract a line from matched category page.
i guess, i'll implement it this weekend.

btw! thanks for using my 4 year old project :)

**Comment by prdpx7** [comment]
Refer #2
